### ISSUE TITLE
Unable to install qrand

### ISSUE THREAD

**Issue by praveentn** [pedrorrivero/qrand#25]
### Describe the bug
Unable to install `qrand` using `pip` in Windows, Colab and IBM Quantum Experience portal.

### To Reproduce
1. Open Python terminal
2. run `pip install qrand`
3. See error

### Expected behavior
Install qrand library

### Error
```
ERROR: Could not find a version that satisfies the requirement qrand
ERROR: No matching distribution found for qrand
```

### Desktop (please complete the following information):
 - Device: all
 - OS: Win, Linux
 - QRAND version: 0.4.0

**Comment by LaurentAjdnik** [comment]
Hi @praveentn!

What is your exact Python version?

`python --version`

Can you try the verbose mode?

`pip install -v qrand`

Do you get this message?

`Link requires a different Python (3.8.8 not in: '>=3.9,<4.0')`

This is indeed the requirement mentioned in the Wheel's Metadata:

`Requires-Python: >=3.9,<4.0`

Weirdly enough, I get this error message about `Python 3.8.8` while I have `Python 3.9.5` installed...

Try this and it might work (it did for me):

`python -m pip install -v qrand`

**Comment by pedrorrivero** [comment]
Hi @praveentn and @LaurentAjdnik , thanks for reaching out. 

To install QRAND you need to be running Python 3.9 or greater (python 3.8 was unstable). 

As @LaurentAjdnik mentions `python -m pip install -v qrand` should fix it as long as the command `python` refers to to a suitable version. You can check this by running `python --version`. Alternatively you can also do `python3 -m pip install -v qrand` provided that `python3 --version` returns Python 3.9.0 or greater. If all of that fails, you can simply invoke the specific python 3.9 binary through `<path/to/python3.9/binary> -m pip install -v qrand`.

Let me know if this helps!

**Comment by praveentn** [comment]
Thanks for the support.

This worked `python -m pip install qrand`, after pointing to 3.9 version of Python.
