### ISSUE TITLE
A few errors when type-checking with mypy

### ISSUE THREAD

**Issue by LaurentAjdnik** [pedrorrivero/qrand#26]
### Describe the bug
* `qrand\platforms\qiskit\backend.py:45: error: Returning Any from function declared to return "Dict[Any, Any]"`
* `qrand\platforms\qiskit\backend.py:49: error: Returning Any from function declared to return "int"`
* `qrand\platforms\qiskit\backend.py:62: error: Returning Any from function declared to return "int"`
* `qrand\platforms\qiskit\backend.py:71: error: Returning Any from function declared to return "int"`
* `qrand\platforms\qiskit\backend.py:81: error: Returning Any from function declared to return "bool"`
* `qrand\platforms\qiskit\circuit.py:37: error: Returning Any from function declared to return "int"`
* `qrand\_qiskit_bit_generator.py:397: error: Returning Any from function declared to return "Dict[Any, Any]"`
* `qrand\platforms\qsharp\job.py:76: error: unused 'type: ignore' comment`
* `qrand\platforms\qsharp\job.py:99: error: Returning Any from function declared to return "List[str]"`
* `qrand\platforms\qsharp\job.py:103: error: Returning Any from function declared to return "List[str]"`
* `Found 10 errors in 4 files (checked 46 source files)`

### To Reproduce
1. Run `mypy` on the module

### Expected behavior
No type-check error thrown by `mypy`.

### Screenshots
Not applicable.

### Desktop (please complete the following information):
 - mypy version: 0.812
 - QRAND version: 0.4.0

### Additional context
Not applicable.

**Comment by pedrorrivero** [comment]
Hi @LaurentAjdnik I am unable to reproduce this issue, even on a fresh install. Can you elaborate?

**Comment by LaurentAjdnik** [comment]
Using these merciless options: 😉

`python -m mypy --ignore-missing-imports --warn-return-any --warn-redundant-casts --warn-unused-ignores qrand`
