### ISSUE TITLE
Random OCTAL, HEX, BASE32, and BASE64

### ISSUE THREAD

**Issue by pedrorrivero** [pedrorrivero/qrand#7]
### Is your feature request related to a problem? Please describe.
There is no functionality for retrieving bitstrings in a more compact base:
- [x] OCTAL
- [x] HEX
- [x] BASE32
- [x] BASE64

### Describe the solution you'd like
Add random hex, base32, and base64 functionality to QRNG

### Describe alternatives you've considered
The user can translate the output bitstring manually

### Additional context
- https://en.wikipedia.org/wiki/Hexadecimal
- https://en.wikipedia.org/wiki/Base32
- https://en.wikipedia.org/wiki/Base64

**Comment by anushkrishnav** [comment]
I can work on HEX, post that will take up other bases too can I just create a function called get_random_hex to achieve this? if not can you elaborate on what is expected

**Comment by pedrorrivero** [comment]
Hi @anushkrishnav! Thanks for showing interest! 

It is my understanding that somebody else is already working on this. They reached out via Discord. Am I right @Avhijit-codeboy? You can maybe work together to get his done.

**Comment by Avhijit-Nair** [comment]
I've actually already implemented all the encodings @pedrorrivero

**Comment by pedrorrivero** [comment]
Awesome @Avhijit-codeboy! It would be nice though if you could chat with @anushkrishnav and see if he has any fresh ideas 🙂 I am assigning this to you two!

**Comment by pedrorrivero** [comment]
Thanks @Avhijit-codeboy, great job!
